
- name: CI

 on:
   workflow_dispatch:
    
jobs:
     runs-on:ubuntu-latest
     
     name: newClone
  uses: GuillaumeFalourd/clone-github-repo-action@v2.3
  with:
    depth: 1
    branch: 'main'
    owner: 'VISHWATEJA1978'
    repository: 'Expense-Sharing'
    
